### ISSUE TITLE
training code 

### ISSUE THREAD

**Issue by antonyvan** [hkproj/pytorch-stable-diffusion#6]
Hello.  Thank you so much for sharing your video and code . I found yours is the most easy one to follow. 
Do you have a plan to write about training code ? Maybe fine tuning the pretrained model with some specific domain data.  
Regards

**Comment by hkproj** [comment]
Duplicate question, already answered here: https://github.com/hkproj/pytorch-stable-diffusion/issues/5#issuecomment-1962781941
